### ISSUE TITLE
Correct "Application/8_uarts_server/bart_metal/8_uart_server" to "Application/8_uarts_server/bare_metal/8_uart_server"

### ISSUE THREAD

**Issue by whatcall** [openwch/ch32v307#10]
Please fix the typo "bart_metal".

[https://github.com/openwch/ch32v307/tree/main/Application/8_uarts_server/bart_metal](url)

**Comment by Taoyukai** [comment]
thank you, typo fixed

**Comment by whatcall** [comment]
Done.
