### ISSUE TITLE
[Suggestion] GB2312 Encoded comments not showing on English Windows

### ISSUE THREAD

**Issue by jpliew** [openwch/ch32v307#18]
May I suggest that all files with GB2312 to be converted into UTF-8 please? This will ensure that Chinese comment show up properly on English Windows. Currently there are some files still in GB2312. Thanks

## Before convert
![image](https://user-images.githubusercontent.com/1773147/168784154-34415f6b-b402-403f-9063-9c25e521469d.png)

## After convert
![image](https://user-images.githubusercontent.com/1773147/168784706-597e3b77-c55c-4018-b88c-e09d4677ae0b.png)

**Comment by HouHou01** [comment]
First of all, thank you for your feedback. EVT encoding format is GBK.
