### ISSUE TITLE
USB and CAN together

### ISSUE THREAD

**Issue by mtx512** [openwch/ch32v307#31]
The datasheet states "_USBD and CAN controller share a dedicated 512-byte SRAM area for data transmission and reception
in the design, so when using USBD and CAN functions at the same time, this shared area needs to be
allocated reasonably to prevent data conflicts._"

Does the sdk support USB and CAN together?

**Comment by HouHou01** [comment]
Hi,
MCU automatic allocation，CH32V307 support USB and CAN together.
