### ISSUE TITLE
Fail to convert data hex file to bin

### ISSUE THREAD

**Issue by berkutta** [openwch/ch32v307#32]
Download from MounRiver Studio seems to be not working. Download via WCHISPTool works fine.

```
------------ Begin flash process of "obj\DHCP.hex" ------------ 
20:24:14:344 >> Current project vendor is WCH, debugger is WCH-Link

20:24:14:344 >> Attempt to open device and upgrade firmware if necessary...
20:24:14:358 >> Fail to convert data hex file to bin

-----------------------------End ------------------------------
```

**Comment by HouHou01** [comment]
Hello,Mrs needs to be updated to V1.81.
Update package download link-
http://www.mounriver.com/download

**Comment by berkutta** [comment]
@HouHou01 Doesn't work with V 1.81

![image](https://user-images.githubusercontent.com/11159719/183352554-1dfe1dcc-bb33-48a9-a1c1-9ea708a42e11.png)

**Comment by berkutta** [comment]
It works with WCH-Link but not with Bootloader

**Comment by HouHou01** [comment]
![image](https://user-images.githubusercontent.com/46395558/183539254-92db04fa-00f8-46ea-b784-9e78f88cb75d.png)
@berkutta
1..Please check whether there is WCH link in the device manager.
2.Please check whether the firmware version of the WCH-Link is correct.
MRS(V1.81)——WCH-Link（REV_0205）

**Comment by HouHou01** [comment]
Try to WCh-Link update the v2.5 firmware.
Refer to https://github.com/HouHou01/Link-Bin
