### ISSUE TITLE
Issue with remapping TIM9

### ISSUE THREAD

**Issue by techlabz** [openwch/ch32v307#50]
Chip: CH32V307VCT6

I am trying to remap TIM9 and it is not working. I did Full Remap to use TIM9_CH2 on PD11, in default configuration(PA3) it works fine. But doesn't seem to work in Full Remap or Partial Remap.

![image](https://user-images.githubusercontent.com/42513204/218594120-66d3635c-1ef2-42df-9f09-17907d3013cc.png)

**Comment by qiyongshuang** [comment]
Thank you for choosing our product. I remapped TIM9 and the function is normal. Attach the main procedure and results. If you have any questions, you can share the program with your permission.
![4](https://user-images.githubusercontent.com/110513727/218633481-5ee9587c-c7db-465c-8de2-966a34c3bb59.png)

**Comment by qiyongshuang** [comment]
Thank you for choosing our product. I remapped TIM9 and the function is normal. Attach the main procedure and results. If you have any questions, you can share the program with your permission.
![1](https://user-images.githubusercontent.com/110513727/218633656-9fae22de-b4a8-4a96-9344-049073bf023b.png)
![2](https://user-images.githubusercontent.com/110513727/218633683-e92dc169-16a6-4fbd-8d26-2446fab33560.png)
![3](https://user-images.githubusercontent.com/110513727/218633721-01449191-c75e-4848-9542-b6b8e0a4ce53.png)
![4](https://user-images.githubusercontent.com/110513727/218633771-eea9ceba-fc0f-4617-b00c-b659b93b9ac4.png)

**Comment by techlabz** [comment]
Hi @qiyongshuang, made silly error, used TIM_OC1Init instead of TIM_OC2Init, thanks again.
