### ISSUE TITLE
IS WCH CH32V307 SUPPORTS UART RS 485 INTERFACE ?

### ISSUE THREAD

**Issue by dharmik52** [openwch/ch32v307#55]
Hello all, 
I have wch ch32v307 board and i have acrel adl 1000 et energy meter which supports rs485 uart interface so my question is that whether i can do this and this mcu board supports UART connections or not? if yes then please explain me , which pin i can use for this interface?

**Comment by qiyongshuang** [comment]
The ch32v307 pin is RS232 level. So you can't connect RS485 serial devices directly.

**Comment by qiyongshuang** [comment]
Ch32v307 outputs TTL level. You may need a level conversion module (TTL to RS485).

**Comment by ktannady** [comment]
is there any modbus communication library for CH32V07? @qiyongshuang
