### ISSUE TITLE
How to check Flash and SRAM usage?

### ISSUE THREAD

**Issue by techlabz** [openwch/ch32v307#57]
Is there a way to check the size of Flash and SRAM usage? I can't seem to find either in the wch download utility tool and mounriver studio, I can see the hex file, but not the actual binary size.

**Comment by qiyongshuang** [comment]
You can generate BIN files through mounriver studio.
Click "file"->choise "properties"
![微信截图_20230313152942](https://user-images.githubusercontent.com/110513727/224635136-e15dd587-8b33-465f-9ffe-96e9aada4323.png)

**Comment by techlabz** [comment]
Hi @qiyongshuang,

What about SRAM/Memory usage?

**Comment by techlabz** [comment]
@qiyongshuang  any luck?

**Comment by qiyongshuang** [comment]
After the project is compiled by MRS:
![image](https://user-images.githubusercontent.com/110513727/226166959-23b19254-3f41-4908-9be9-a4b22a884f48.png)
flash=data+dec;
rom=data+bss;

**Comment by qiyongshuang** [comment]
After the project is compiled by MRS:
![image](https://user-images.githubusercontent.com/110513727/226167054-93340a22-7682-4234-ac98-eb7403b2adb7.png)
flash=data+dec;
SRAM=data+bss;
