### ISSUE TITLE
Datasheet English translation

### ISSUE THREAD

**Issue by michele-perrone** [openwch/ch32v307#6]
Hi! I was wondering if there are any plans to provide an English translation for the complete datasheet.  
I could find it only in Chinese: http://www.wch.cn/downloads/file/371.html

The datasheet that is currently available [in this repository](https://github.com/openwch/ch32v307/blob/main/Datasheet/CH32V20x_30xDS0.PDF) is the English version of [this document](http://www.wch.cn/downloads/file/355.html), which does not include the detailed descriptions of each bit in the registers.

Thank you in advance!  
Michele

**Comment by Tonymac32** [comment]
I second this, and thank you @michele-perrone for also linking the full (if untranslated) document

**Comment by HouHou01** [comment]
First of all, thank you for your feedback。English version of the complete registers datasheet is being translated。When finished, it will be placed in this repository.

**Comment by michele-perrone** [comment]
Thank you. This will be much welcome.
