### ISSUE TITLE
Custom bootloader

### ISSUE THREAD

**Issue by robots** [openwch/ch32v307#62]
Datasheet states that all flash areas except "Vendor data" can be user operated. Can you please give example how to erase and program bootloader area ? I would like to develop custom bootloader residing in Bootloader area. Thank you.

![shot-2023-04-18_17-38-06](https://user-images.githubusercontent.com/204234/232829517-b558d715-6a2f-4f67-81cf-b78515d4af1f.jpg)

**Comment by qiyongshuang** [comment]
If you want to updata fireware,you can refer EVT\IAP.
