### ISSUE TITLE
Clarification on TIM5 bitness

### ISSUE THREAD

**Issue by scomx** [openwch/ch32v307#74]
Hi,

MCU: CH32V307

In the datasheet p.14 TIM5 resolution is said to be 16/32 bits while the other general purpose timers are all 16 bit. I can't seem to find additional info on what this means or how to make TIM5 32 bits. 

TIM_TimeBaseInitTypeDef struct is uint16_t only. So what does the datasheet "TIM5 16/32 bits" actually signify, e.g. what steps are required to make TIM5 32 bit resolution?

EDIT: Corrected some mistakes.

**Comment by qiyongshuang** [comment]
![image](https://github.com/openwch/ch32v307/assets/110513727/0f7c3255-e623-486b-8bb8-b5d060a9e2f9)
