### ISSUE TITLE
ch32v30x_usb.h is missing

### ISSUE THREAD

**Issue by bsdinis1** [openwch/ch32v307#82]
The file "ch32v30x_usb.h" is missing.

**Comment by guide-admin** [comment]
ты решил проблему?

**Comment by guide-admin** [comment]
короче ребят берете этот файл "ch32v30x_usb.h" и качайте его потом его надо ставить в \workspace для MRS\ваш проект\Peripheral и все у вас будет работать а файл "ch32v30x_usb.h" можно скачать с "https://gitea.alexisvl.rocks/alexisvl/ch32vusb_cdc" вы там найдете этот файл.
